### ISSUE TITLE
Error: No compatible device found

### ISSUE THREAD

**Issue by ducan-ne** [DioxusLabs/blitz#154]
I’m getting an error when trying to run Blitz (https://github.com/DioxusLabs/blitz) on a server. Are there any native dependencies required to run Blitz? I suspect the issue might be GPU-related, as my server only has CPU.

The error is triggered by this code: https://github.com/DioxusLabs/blitz/blob/5caf93c7a7e1edc24f93f204d0e15593f7be3513/packages/blitz-renderer-vello/src/renderer.rs#L181

**Comment by nicoburns** [comment]
You likely won't be able to run the current version of Blitz on a server that doesn't have a GPU. This is because of our dependency on `wgpu` (via `vello`) for rendering. There are two ways in which this could be made to work:

- Use a server with a GPU
- Someone could write an alternative to `blitz-renderer-vello` using a different rendering backend which supports CPU-only rendering (for example, `skia`)

That's definitely something I would like to do long-term. But isn't on our short-term roadmap. I'd be happy to provide pointers if this is something that you would be interested in implementing.

**Comment by nicoburns** [comment]
@ducan-ne I've discovered a 3rd approach. Install software GPU emulation:

See https://github.com/linebender/vello/blob/main/.github/workflows/ci.yml#L210

**Comment by nicoburns** [comment]
I'm going to close this one, but I've opened https://github.com/DioxusLabs/blitz/issues/157 to track the cpu-renderer feature.
